# Generated by Django 6.0.4 on 2026-05-10 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Кличка')),
                ('age', models.IntegerField(verbose_name='Вік')),
                ('is_vaccinated', models.BooleanField(default=False, verbose_name='Вакцинований')),
            ],
        ),
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва притулку')),
                ('address', models.CharField(max_length=255, verbose_name='Адреса')),
                ('capacity', models.IntegerField(default=10, verbose_name='Місткість')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkup_date', models.DateField(auto_now_add=True, verbose_name='Дата огляду')),
                ('diagnosis', models.TextField(verbose_name='Діагноз/Стан')),
                ('weight', models.FloatField(verbose_name='Вага (кг)')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_history', to='calculator.cat', verbose_name='Кіт')),
            ],
        ),
        migrations.AddField(
            model_name='cat',
            name='shelter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cats', to='calculator.shelter', verbose_name='Притулок'),
        ),
    ]
