# Generated by Django 6.0.4 on 2026-05-10 22:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='arrival_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата прибуття'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cat',
            name='breed',
            field=models.CharField(blank=True, max_length=50, verbose_name='Порода'),
        ),
        migrations.AddField(
            model_name='cat',
            name='character',
            field=models.CharField(blank=True, max_length=100, verbose_name='Характер'),
        ),
        migrations.AddField(
            model_name='cat',
            name='color',
            field=models.CharField(blank=True, max_length=30, verbose_name='Окрас'),
        ),
        migrations.AddField(
            model_name='cat',
            name='gender',
            field=models.CharField(choices=[('M', 'Кіт'), ('F', 'Кішка')], default='M', max_length=1, verbose_name='Стать'),
        ),
        migrations.AddField(
            model_name='cat',
            name='history',
            field=models.TextField(blank=True, verbose_name='Історія котика'),
        ),
        migrations.AddField(
            model_name='cat',
            name='is_adopted',
            field=models.BooleanField(default=False, verbose_name='Прилаштований'),
        ),
        migrations.AddField(
            model_name='cat',
            name='is_sterilized',
            field=models.BooleanField(default=False, verbose_name='Стерилізований'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='next_visit',
            field=models.DateField(blank=True, null=True, verbose_name='Наступний огляд'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='recommendations',
            field=models.TextField(blank=True, verbose_name='Рекомендації'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='temperature',
            field=models.FloatField(blank=True, null=True, verbose_name='Температура'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='treatment',
            field=models.TextField(blank=True, verbose_name='Лікування'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='vet_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ветеринар'),
        ),
        migrations.AddField(
            model_name='shelter',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='shelter',
            name='has_vet',
            field=models.BooleanField(default=False, verbose_name='Є власний ветеринар'),
        ),
        migrations.AddField(
            model_name='shelter',
            name='opened_since',
            field=models.DateField(blank=True, null=True, verbose_name='Дата відкриття'),
        ),
        migrations.AddField(
            model_name='shelter',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='shelter',
            name='website',
            field=models.URLField(blank=True, verbose_name='Вебсайт'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='age',
            field=models.FloatField(verbose_name='Вік'),
        ),
    ]
