# Generated by Django 6.0.4 on 2026-05-10 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_cat_arrival_date_cat_breed_cat_character_cat_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='checkup_date',
            field=models.DateField(verbose_name='Дата огляду'),
        ),
    ]
