# Generated by Django 6.0.4 on 2026-05-11 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_alter_medicalrecord_checkup_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shelter',
            name='opened_since',
        ),
        migrations.AddField(
            model_name='shelter',
            name='working_hours',
            field=models.CharField(blank=True, max_length=100, verbose_name='Години роботи'),
        ),
    ]
