# Generated by Django 6.0.4 on 2026-05-11 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0004_remove_shelter_opened_since_shelter_working_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='arrival_date',
            field=models.DateField(verbose_name='Дата прибуття'),
        ),
    ]
