# Generated by Django 6.0.4 on 2026-05-12 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0005_alter_cat_arrival_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='cats_photos/', verbose_name='Фото'),
        ),
    ]
