# Generated by Django 6.0.4 on 2026-05-12 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0006_cat_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelter',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='shelters_photos/', verbose_name='Фото притулку'),
        ),
    ]
