# Generated by Django 6.0.4 on 2026-05-13 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0007_shelter_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='breed_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Порода'),
        ),
        migrations.AddField(
            model_name='cat',
            name='breed_uk',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Порода'),
        ),
        migrations.AddField(
            model_name='cat',
            name='character_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Характер'),
        ),
        migrations.AddField(
            model_name='cat',
            name='character_uk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Характер'),
        ),
        migrations.AddField(
            model_name='cat',
            name='color_en',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Окрас'),
        ),
        migrations.AddField(
            model_name='cat',
            name='color_uk',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Окрас'),
        ),
        migrations.AddField(
            model_name='cat',
            name='history_en',
            field=models.TextField(blank=True, null=True, verbose_name='Історія котика'),
        ),
        migrations.AddField(
            model_name='cat',
            name='history_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Історія котика'),
        ),
        migrations.AddField(
            model_name='cat',
            name='name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Кличка'),
        ),
        migrations.AddField(
            model_name='cat',
            name='name_uk',
            field=models.CharField(max_length=50, null=True, verbose_name='Кличка'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='diagnosis_en',
            field=models.TextField(null=True, verbose_name='Діагноз/Стан'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='diagnosis_uk',
            field=models.TextField(null=True, verbose_name='Діагноз/Стан'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='recommendations_en',
            field=models.TextField(blank=True, null=True, verbose_name='Рекомендації'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='recommendations_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Рекомендації'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='treatment_en',
            field=models.TextField(blank=True, null=True, verbose_name='Лікування'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='treatment_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Лікування'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='vet_name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ветеринар'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='vet_name_uk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ветеринар'),
        ),
        migrations.AddField(
            model_name='shelter',
            name='address_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Адреса'),
        ),
        migrations.AddField(
            model_name='shelter',
            name='address_uk',
            field=models.CharField(max_length=255, null=True, verbose_name='Адреса'),
        ),
        migrations.AddField(
            model_name='shelter',
            name='capacity_en',
            field=models.IntegerField(default=10, null=True, verbose_name='Місткість'),
        ),
        migrations.AddField(
            model_name='shelter',
            name='capacity_uk',
            field=models.IntegerField(default=10, null=True, verbose_name='Місткість'),
        ),
        migrations.AddField(
            model_name='shelter',
            name='has_vet_en',
            field=models.BooleanField(default=False, verbose_name='Є власний ветеринар'),
        ),
        migrations.AddField(
            model_name='shelter',
            name='has_vet_uk',
            field=models.BooleanField(default=False, verbose_name='Є власний ветеринар'),
        ),
        migrations.AddField(
            model_name='shelter',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Назва притулку'),
        ),
        migrations.AddField(
            model_name='shelter',
            name='name_uk',
            field=models.CharField(max_length=100, null=True, verbose_name='Назва притулку'),
        ),
        migrations.AddField(
            model_name='shelter',
            name='working_hours_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Години роботи'),
        ),
        migrations.AddField(
            model_name='shelter',
            name='working_hours_uk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Години роботи'),
        ),
    ]
