# Generated by Django 6.0.4 on 2026-05-14 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0008_cat_breed_en_cat_breed_uk_cat_character_en_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shelter',
            name='capacity_en',
        ),
        migrations.RemoveField(
            model_name='shelter',
            name='capacity_uk',
        ),
        migrations.RemoveField(
            model_name='shelter',
            name='has_vet_en',
        ),
        migrations.RemoveField(
            model_name='shelter',
            name='has_vet_uk',
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.cat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'cat')},
            },
        ),
    ]
