# Generated by Django 6.0.4 on 2026-05-14 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0011_usersessionlog_delete_usersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='breed_de',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Порода'),
        ),
        migrations.AddField(
            model_name='cat',
            name='character_de',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Характер'),
        ),
        migrations.AddField(
            model_name='cat',
            name='color_de',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Окрас'),
        ),
        migrations.AddField(
            model_name='cat',
            name='history_de',
            field=models.TextField(blank=True, null=True, verbose_name='Історія котика'),
        ),
        migrations.AddField(
            model_name='cat',
            name='name_de',
            field=models.CharField(max_length=50, null=True, verbose_name='Кличка'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='diagnosis_de',
            field=models.TextField(null=True, verbose_name='Діагноз/Стан'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='recommendations_de',
            field=models.TextField(blank=True, null=True, verbose_name='Рекомендації'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='treatment_de',
            field=models.TextField(blank=True, null=True, verbose_name='Лікування'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='vet_name_de',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ветеринар'),
        ),
        migrations.AddField(
            model_name='shelter',
            name='address_de',
            field=models.CharField(max_length=255, null=True, verbose_name='Адреса'),
        ),
        migrations.AddField(
            model_name='shelter',
            name='name_de',
            field=models.CharField(max_length=100, null=True, verbose_name='Назва притулку'),
        ),
        migrations.AddField(
            model_name='shelter',
            name='working_hours_de',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Години роботи'),
        ),
    ]
